### ISSUE TITLE
Python 3 Support

### ISSUE THREAD

**Issue by mikepianka** [crackernutter/EsriRESTScraper#9]
Any plans for refactoring to support Python 3 since Python 2 has been officially depreciated?

**Comment by crackernutter** [comment]
Yes! I'm actually working on this right now - I think its about done - I just need to push the changes....

**Comment by crackernutter** [comment]
@mikepianka I just pushed a Python 3 branch (which should be backwards compatible with Python 2) and updated the documentation.  I'm still running some tests, but feel free to pull this branch now to use and test yourself, since I likely won't capture all edge cases.  Once I'm happy with the tests, I'll merge with the master branch.
